# Site settings
url: "https://junrongchen2004.github.io"   # full site URL
baseurl: ""                                 # user sites must use empty baseurl

title: "Junrong Chen"
email: "juc036@ucsd.edu"                    # optional
description: "Your short tagline here"
timezone: "PDT/PST"             # optional; helps with dates

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

collections:
  - publications
  - news
  - showcase

